export const accountEn = {
  help: "Your personal account keeps your routes and preferences. Website access is separate.",
  password: "Password", confirm: "Confirm password", show: "Show password", hide: "Hide password",
  login: "Sign in with password", signup: "Create account", forgot: "Forgot password?", link: "Use an email link",
  back: "Back to sign in", reset: "Request password reset", resend: "Resend confirmation email",
  lengthRule: "At least 8 characters", upperRule: "One uppercase letter (A–Z)", lowerRule: "One lowercase letter (a–z)", numberRule: "One number (0–9)", symbolRule: "One symbol, such as ! or @", ruleMet: "met", ruleMissing: "needed",
  passwordHelp: "Use at least 8 characters, including uppercase and lowercase letters, a number and a symbol.", mismatch: "The passwords do not match.",
  weak: "Include at least 8 characters, an uppercase letter, a lowercase letter, a number and a symbol.",
  confirmation: "Confirmation requested. If this address can be registered, check your inbox and spam folder. Confirm your email before signing in.",
  resetRequested: "Reset requested. If an account exists for this address, check your inbox and spam folder. Open the newest link to choose a new password.",
  invalidLogin: "Unable to sign in. Check your email and password, or reset your password.",
  unconfirmed: "Confirm your email before signing in. You can request a new confirmation below.",
  unavailable: "Email could not be requested. Try again later or continue with Google.",
  expired: "This account link is invalid, expired or already used. Request a new link below.",
  resetTitle: "Choose a new password", change: "Change password", save: "Save new password",
  resetHelp: "Choose a new password for this personal account.", saved: "Your password has been updated.",
  changedAccount: "Your account session changed. Close this form and sign in again.",
  recentLogin: "Sign in again, or request a fresh password reset link, before changing your password.",
  signupDisabled: "New accounts are not available right now. Existing users can sign in.",
  confirmed: "Your account link was accepted. You are signed in.", waiting: "Checking your account link…",
};
export const accountAr: typeof accountEn = {
  help: "يحفظ حسابك الشخصي مساراتك وتفضيلاتك. دخول الموقع منفصل عن حسابك.",
  password: "كلمة المرور", confirm: "تأكيد كلمة المرور", show: "إظهار كلمة المرور", hide: "إخفاء كلمة المرور",
  login: "تسجيل الدخول بكلمة المرور", signup: "إنشاء حساب", forgot: "نسيت كلمة المرور؟", link: "استخدام رابط عبر البريد",
  back: "العودة لتسجيل الدخول", reset: "طلب إعادة تعيين كلمة المرور", resend: "إعادة إرسال رسالة التأكيد",
  lengthRule: "8 محارف على الأقل", upperRule: "حرف إنجليزي كبير (A–Z)", lowerRule: "حرف إنجليزي صغير (a–z)", numberRule: "رقم واحد (0–9)", symbolRule: "رمز واحد مثل ! أو @", ruleMet: "مستوفى", ruleMissing: "مطلوب",
  passwordHelp: "استخدم 8 محارف على الأقل، مع حرف إنجليزي كبير وآخر صغير ورقم ورمز.", mismatch: "كلمتا المرور غير متطابقتين.",
  weak: "يجب أن تتضمن كلمة المرور 8 محارف على الأقل وحرفاً إنجليزياً كبيراً وصغيراً ورقماً ورمزاً.",
  confirmation: "تم طلب رسالة التأكيد. إذا كان العنوان قابلاً للتسجيل، تحقق من بريدك والبريد غير المرغوب فيه. أكّد بريدك قبل تسجيل الدخول.",
  resetRequested: "تم طلب إعادة التعيين. إذا كان لهذا العنوان حساب، تحقق من بريدك والبريد غير المرغوب فيه. افتح أحدث رابط لاختيار كلمة مرور جديدة.",
  invalidLogin: "تعذّر تسجيل الدخول. تحقق من البريد وكلمة المرور أو أعد تعيين كلمة المرور.",
  unconfirmed: "أكّد بريدك قبل تسجيل الدخول. يمكنك طلب رسالة تأكيد جديدة أدناه.",
  unavailable: "تعذّر طلب الرسالة. حاول لاحقاً أو تابع باستخدام Google.",
  expired: "رابط الحساب غير صالح أو منتهي الصلاحية أو مستخدم سابقاً. اطلب رابطاً جديداً أدناه.",
  resetTitle: "اختيار كلمة مرور جديدة", change: "تغيير كلمة المرور", save: "حفظ كلمة المرور الجديدة",
  resetHelp: "اختر كلمة مرور جديدة لهذا الحساب الشخصي.", saved: "تم تحديث كلمة المرور.",
  changedAccount: "تغيّرت جلسة حسابك. أغلق النموذج وسجّل الدخول مجدداً.",
  recentLogin: "سجّل الدخول مجدداً أو اطلب رابط إعادة تعيين جديداً قبل تغيير كلمة المرور.",
  signupDisabled: "إنشاء حسابات جديدة غير متاح حالياً. يمكن للمستخدمين الحاليين تسجيل الدخول.",
  confirmed: "تم قبول رابط حسابك وتسجيل دخولك.", waiting: "جارٍ التحقق من رابط حسابك…",
};
