export const coreEn = {
  "goalLabel": "What matters most?",
  "goalShortest": "Shortest drive",
  "goalSoonest": "Arrive soonest",
  "goalShortestHelp": "Least driving time among checked feasible departures; waiting may be longer.",
  "goalSoonestHelp": "Earliest estimated arrival among checked feasible departures; the drive may be longer.",
  "goalsReuse": "Changing this goal reuses checked forecasts without another traffic request.",
  "endsNextDay": "Ends next day",
  "arrivePrompt": "I need to arrive between these times. Departure can be earlier.",
  "leavePrompt": "I can leave between these times. Compare driving time and arrival.",
  "alternatives": "Other checked choices",
  "estimateOnly": "Provider estimates; route accuracy has not been validated. Coverage annotations do not guarantee ETA accuracy.",
  "partialCoverage": "Traffic data is partial or unknown. These are estimated driving times, not measured congestion.",
  "unvalidatedRoute": "Traffic recommendations for Libya are withheld while the reported ETA discrepancy is investigated. Listed timing estimates need independent verification.",
  "selectUnvalidated": "No traffic recommendation. You may inspect a checked estimate below.",
  "partialResults": "Some checks are missing or the request limit was reached. Compare only available checks.",
  "checkedTable": "Checked departures table",
  "choose": "Select",
  "outsideBounds": "Outside your window",
  "missingChecks": "Unavailable departure checks",
  "unknownArrival": "Arrival unavailable",
  "failedCount": "missing checks",
  "cancelCheck": "Cancel check",
  "cancelHelp": "Cancelled locally. Provider work already started may still use your allowance.",
  "retryCheckHelp": "Retry uses your analysis allowance; requests already started may have been counted.",
  "dateAdjusted": "Saved window restored for its next usable date:",
  "gpsAccuracy": "Location accuracy",
  "meters": "m",
  "capturedAt": "Location captured at",
  "mapRetry": "Retry map",
  "mapSessionHelp": "Sign in again to load the map. You can still enter locations manually.",
  "mapAccessHelp": "Map access was declined. Your forecast results remain available; retry after map access is restored.",
  "mapAllowanceHelp": "The map request limit was reached. Try again later; available forecast results are unchanged.",
  "mapBrowserHelp": "This browser could not start the map graphics. Try another browser; you can still plan with manual locations.",
  "mapNetworkHelp": "Map content could not load. Check your connection and retry; your forecast results remain available.",
  "mapLabelsHelp": "Arabic map labels could not load. Retry the map; pins and journey results remain available.",
  "dateError": "Choose a valid travel date within the next seven days.",
  "boundsError": "Choose an end after the start, up to 24 hours. Use Ends next day for overnight travel.",
  "bufferError": "Choose 0–60 minutes; your arrival window must fit this allowance."
};
export const coreAr: typeof coreEn = {
  "goalLabel": "ما الأهم لك؟",
  "goalShortest": "أقصر قيادة",
  "goalSoonest": "الوصول بأسرع وقت",
  "goalShortestHelp": "أقل مدة قيادة بين الانطلاقات المختبرة المناسبة؛ قد تنتظر أكثر.",
  "goalSoonestHelp": "أبكر وصول متوقع بين الانطلاقات المختبرة المناسبة؛ قد تكون القيادة أطول.",
  "goalsReuse": "تغيير الهدف يعيد ترتيب التوقعات المختبرة دون طلب مرور جديد.",
  "endsNextDay": "تنتهي في اليوم التالي",
  "arrivePrompt": "أحتاج الوصول بين هذين الوقتين. قد يكون الانطلاق قبلهما.",
  "leavePrompt": "يمكنني الانطلاق بين هذين الوقتين. قارن مدة القيادة والوصول.",
  "alternatives": "خيارات أخرى مختبرة",
  "estimateOnly": "تقديرات المزود؛ لم تُتحقق دقة هذه الرحلة. بيانات التغطية لا تضمن دقة وقت الوصول.",
  "partialCoverage": "بيانات المرور جزئية أو غير معروفة. هذه مدد قيادة متوقعة وليست قياساً للازدحام.",
  "unvalidatedRoute": "توصيات المرور في ليبيا موقوفة إلى حين فحص اختلاف وقت الوصول المُبلغ عنه. يجب التحقق مستقلاً من تقديرات الوقت المعروضة.",
  "selectUnvalidated": "لا توجد توصية مرور. يمكنك الاطلاع على تقدير مختبر أدناه.",
  "partialResults": "بعض التوقعات مفقودة أو بلغ الطلب حده. قارن التوقعات المتاحة فقط.",
  "checkedTable": "جدول الانطلاقات المختبرة",
  "choose": "اختيار",
  "outsideBounds": "خارج الفترة المختارة",
  "missingChecks": "توقعات الانطلاق غير المتاحة",
  "unknownArrival": "الوصول غير متاح",
  "failedCount": "توقعات غير متاحة",
  "cancelCheck": "إلغاء التحقق",
  "cancelHelp": "أُلغي الطلب محلياً. قد تستهلك أعمال المزود التي بدأت بالفعل من حصتك.",
  "retryCheckHelp": "إعادة المحاولة تستهلك من حصة التحليلات؛ قد تكون الطلبات التي بدأت قد احتُسبت.",
  "dateAdjusted": "أُعيدت الفترة المحفوظة إلى أقرب تاريخ صالح:",
  "gpsAccuracy": "دقة الموقع",
  "meters": "م",
  "capturedAt": "التقط الموقع في",
  "mapRetry": "إعادة تحميل الخريطة",
  "mapSessionHelp": "سجّل الدخول مجدداً لتحميل الخريطة. يمكنك إدخال المواقع يدوياً.",
  "mapAccessHelp": "رُفض الوصول إلى الخريطة. نتائج التوقعات متاحة؛ أعد المحاولة بعد استعادة الوصول.",
  "mapAllowanceHelp": "بلغت طلبات الخريطة حدها. حاول لاحقاً؛ نتائج التوقعات المتاحة لم تتغير.",
  "mapBrowserHelp": "تعذر على هذا المتصفح تشغيل رسوم الخريطة. جرّب متصفحاً آخر؛ يمكنك التخطيط بإدخال المواقع يدوياً.",
  "mapNetworkHelp": "تعذر تحميل محتوى الخريطة. تحقق من الاتصال وأعد المحاولة؛ نتائج التوقعات متاحة.",
  "mapLabelsHelp": "تعذر تحميل أسماء الخريطة العربية. أعد تحميل الخريطة؛ العلامات ونتائج الرحلة متاحة.",
  "dateError": "اختر تاريخ رحلة صالحاً خلال الأيام السبعة القادمة.",
  "boundsError": "اختر نهاية بعد البداية، بحد أقصى 24 ساعة. اختر اليوم التالي للرحلات الليلية.",
  "bufferError": "اختر من 0 إلى 60 دقيقة؛ يجب أن تتسع فترة الوصول لهذا الهامش."
};
