import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api} from './api';
import type {AppConfig} from '../shared/types';
import {en,ar} from './i18n';
import {Button,Notice,Pending,displayFailure} from './feedback';
const copy={en:{loading:'Loading usage…',retry:'Retry owner dashboard',cancel:'Discard changes',roles:'Daily analysis allowances',roleHelp:'One daily analysis checks multiple departures. Week consumes one analysis per checked day. Allowances reset at midnight UTC; provider caps and the spending gate still apply.',override:'Account override',account:'Account',inherit:'Use role default',limit:'Daily limit',saved:'Owner settings saved.',failed:'Owner information could not load.',unsaved:'Unsaved owner changes.',default:'Role default',users:'Account overrides',soft:'Soft threshold',free:'Configured free cap',period:'Period',rpm:'Requests / minute'},ar:{loading:'جارٍ تحميل الاستخدام…',retry:'إعادة تحميل لوحة المالك',cancel:'تجاهل التغييرات',roles:'حصص التحليل اليومية',roleHelp:'يفحص التحليل اليومي عدة أوقات مغادرة. يستهلك الأسبوع تحليلاً لكل يوم مفحوص. تُصفّر الحصص عند منتصف الليل بتوقيت UTC؛ تبقى حدود المزوّد وحماية الإنفاق سارية.',override:'حصة خاصة بالحساب',account:'الحساب',inherit:'استخدام حصة الدور',limit:'الحد اليومي',saved:'تم حفظ إعدادات المالك.',failed:'تعذّر تحميل بيانات المالك.',unsaved:'تغييرات المالك غير محفوظة.',default:'حصة الدور',users:'حصص الحسابات الخاصة',soft:'حد التنبيه',free:'الحد المجاني المضبوط',period:'الفترة',rpm:'طلبات / دقيقة'}};
export default function Owner({role,config,locale,account}:{role:string;config:AppConfig;locale:'en'|'ar';account:string|null}) {
 const t=locale==='ar'?ar:en,c=copy[locale];
 const q=useQuery({queryKey:['admin',role,account],enabled:role==='admin'&&Boolean(account),queryFn:({signal})=>api<any>('/api/admin/overview',undefined,undefined,signal,account!)});
 const users=useQuery({queryKey:['admin-users',account],enabled:role==='admin'&&Boolean(account),queryFn:({signal})=>api<any[]>('/api/admin/users',undefined,undefined,signal,account!)});
 const [draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[target,setTarget]=useState(''),[limit,setLimit]=useState('');
 useEffect(()=>{setDraft(null);setError('');setNotice('');setTarget('');setLimit('');},[account]);
 useEffect(()=>{if(q.data&&!draft)setDraft(structuredClone(q.data.config));},[q.data,draft]);
 async function save(override=false){if(!account||!draft)return;setBusy(true);setError('');setNotice('');try{const body=override?{userAllowance:{userId:target,limit:limit===''?null:Number(limit)}}:{paid:draft.paid,monthlyBudget:Number(draft.monthlyBudget),providers:Object.fromEntries(Object.entries(draft.providers).map(([name,value]:[string,any])=>[name,{enabled:value.enabled,hard:Number(value.hard)}])),countries:draft.countries,allowances:draft.allowances};await api('/api/admin/config',body,'PATCH',undefined,account);const result=await q.refetch();if(result.data)setDraft(structuredClone(result.data.config));setNotice(c.saved);}catch(e){setError(displayFailure(e,locale));}finally{setBusy(false);}}
 if(role!=='admin')return <section className="panel empty-state"><h1>{t.owner}</h1><p>{config.authConfigured?t.needsOwner:t.ownerSetup}</p></section>;
 const dirty=draft&&q.data&&JSON.stringify(draft)!==JSON.stringify(q.data.config);
 return <><div className="page-heading"><div><h1>{t.quotaTitle}</h1><p>{t.quotaHelp}</p></div></div>{q.isPending&&<Pending>{c.loading}</Pending>}{q.isError&&<><Notice>{c.failed}</Notice><Button onClick={()=>void q.refetch()}>{c.retry}</Button></>}{error&&<Notice>{error}</Notice>}{notice&&<p role="status">{notice}</p>}
 {draft&&q.data&&<><fieldset disabled={busy} className="owner-editor"><legend className="sr-only">{t.owner}</legend><section className="panel budget-panel"><label className="check-label"><input type="checkbox" checked={draft.paid} onChange={e=>setDraft({...draft,paid:e.target.checked})}/>{t.paid}</label><label>{t.budgetUsd}<input type="number" min={0} max={1000} value={draft.monthlyBudget} onChange={e=>setDraft({...draft,monthlyBudget:e.target.value})}/></label></section>
 <section className="panel provider-panel"><div className="table-scroll"><table><caption>{t.provider}</caption><thead><tr><th>{t.provider}</th><th>{t.used}</th><th>{t.hardCap}</th><th>{t.enabled}</th><th>{c.free}</th><th>{c.period}</th><th>{c.rpm}</th></tr></thead><tbody>{Object.entries(draft.providers).map(([provider,p]:[string,any])=><tr key={provider}><th scope="row">{provider}</th><td>{Object.entries(q.data.usage).filter(([key])=>key.startsWith(`p:${provider}:`)).reduce((n,[,v])=>n+Number(v),0)}</td><td><input aria-label={`${provider} ${t.hardCap}`} type="number" min={0} max={10000000} value={p.hard} onChange={e=>setDraft({...draft,providers:{...draft.providers,[provider]:{...p,hard:e.target.value}}})}/></td><td><input type="checkbox" aria-label={`${provider} ${t.enabled}`} checked={p.enabled} onChange={e=>setDraft({...draft,providers:{...draft.providers,[provider]:{...p,enabled:e.target.checked}}})}/></td><td>{p.free}</td><td>{p.period==='day'?(locale==='ar'?'يوم':'day'):(locale==='ar'?'شهر':'month')}</td><td>{p.rpm}</td></tr>)}</tbody></table></div></section>
 <div className="settings-grid"><section className="panel"><h2>{t.countryRules}</h2>{Object.entries(draft.countries).map(([country,primary])=><label key={country}>{t[country as 'JO']}<select value={String(primary)} onChange={e=>setDraft({...draft,countries:{...draft.countries,[country]:e.target.value}})}><option value="mapbox">Mapbox</option><option value="google">Google</option></select></label>)}<h2>{t.accuracy}</h2><p>{t.accuracyHelp}</p></section><section className="panel"><h2>{c.roles}</h2><p>{c.roleHelp}</p>{Object.entries(draft.allowances??{guest:1,user:10,family:30,admin:100}).map(([role,value])=><label key={role}>{({en:{guest:'Guest',user:'User',family:'Family',admin:'Owner'},ar:{guest:'ضيف',user:'مستخدم',family:'عائلة',admin:'مالك'}}[locale] as any)[role]}<input aria-label={`${role} ${c.limit}`} type="number" min={0} max={1000} value={Number(value)} onChange={e=>setDraft({...draft,allowances:{...draft.allowances,[role]:Number(e.target.value)}})}/></label>)}</section></div>
 {dirty&&<p role="status">{c.unsaved}</p>}<div className="settings-actions"><Button pending={busy} disabled={!dirty} onClick={()=>void save()}>{t.saveChanges}</Button><Button className="button secondary" disabled={!dirty} onClick={()=>{setDraft(structuredClone(q.data.config));setError('');}}>{c.cancel}</Button></div></fieldset>
 <section className="panel"><h2>{c.override}</h2>{users.isPending&&<Pending>{c.loading}</Pending>}{users.isError&&<><Notice>{c.failed}</Notice><Button onClick={()=>void users.refetch()}>{c.retry}</Button></>}<label>{c.account}<select value={target} disabled={busy||dirty} onChange={e=>{setTarget(e.target.value);setLimit(String(q.data.config.userAllowances?.[e.target.value]??''));}}><option value="">—</option>{users.data?.map(u=><option key={u.id} value={u.id}>{u.id} · {u.role}</option>)}</select></label><label>{c.limit}<input type="number" min={0} max={1000} placeholder={c.inherit} value={limit} disabled={busy||dirty||!target} onChange={e=>setLimit(e.target.value)}/></label><p>{c.inherit}: {q.data.config.userAllowances?.[target]??c.default}</p><div className="settings-actions"><Button pending={busy} disabled={!target||dirty} onClick={()=>void save(true)}>{t.saveChanges}</Button><Button className="button secondary" disabled={busy||!target} onClick={()=>setLimit(String(q.data.config.userAllowances?.[target]??''))}>{c.cancel}</Button></div></section>
 <div className="settings-grid"><section className="panel"><h2>{t.audit}</h2>{q.data.audit.length?q.data.audit.slice(0,10).map((v:any,i:number)=><p key={i}><bdi>{new Date(v.at).toLocaleString(locale)}</bdi> · <code>{JSON.stringify(v.change)}</code></p>):<p>{t.noAudit}</p>}</section><section className="panel"><h2>{t.errors}</h2>{q.data.errors.length?q.data.errors.slice(0,10).map((v:any,i:number)=><p key={i}><bdi>{v.code} · {new Date(v.at).toLocaleString(locale)} · {v.requestId}</bdi></p>):<p>{t.noErrors}</p>}</section></div></> }</>;
}
