import {useEffect,useState} from 'react';
import type {Candidate,Plan} from '../shared/types';
import {reminderEligible} from '../shared/reminders';
import {api} from './api';
import {Button,Notice,Pending,displayFailure} from './feedback';
import {clock,dateLabel,localDate} from '../shared/time';
const words={en:{title:'Journey reminders',lead:'Minutes before departure',save:'Remind me of this departure',cancel:'Cancel reminder',retry:'Retry reminders',empty:'No upcoming reminders.',saved:'Reminder scheduled on your enabled devices.',cancelled:'Reminder cancelled.',help:'Delivery is checked every ten minutes and also depends on your phone connection. This is a reminder of the selected estimate; traffic is not rechecked automatically.',enable:'Enable device notifications in Settings first.',signIn:'Sign in to schedule and view your personal reminders.',blocked:'Reminders are unavailable for this unvalidated route or departure.',failed:'Reminders could not load.'},ar:{title:'تذكيرات الرحلة',lead:'دقائق قبل المغادرة',save:'ذكّرني بهذه المغادرة',cancel:'إلغاء التذكير',retry:'إعادة تحميل التذكيرات',empty:'لا توجد تذكيرات قادمة.',saved:'تمت جدولة التذكير على أجهزتك المفعّلة.',cancelled:'تم إلغاء التذكير.',help:'تُفحص التذكيرات كل عشر دقائق ويعتمد وصولها على اتصال هاتفك. يذكّرك الإشعار بالتقدير المختار؛ لا يُعاد فحص حركة المرور تلقائياً.',enable:'فعّل إشعارات الجهاز من الإعدادات أولاً.',signIn:'سجّل الدخول لجدولة تذكيراتك الشخصية وعرضها.',blocked:'التذكيرات غير متاحة لهذا المسار غير المتحقق منه أو موعد المغادرة.',failed:'تعذّر تحميل التذكيرات.'}};
export default function ReminderControls({locale,account,push,plan,candidate,list=false}:{locale:'en'|'ar';account:string|null;push:boolean;plan?:Plan;candidate?:Candidate|null;list?:boolean}) {
 const t=words[locale],[lead,setLead]=useState(20),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[rows,setRows]=useState<any[]>([]),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;setRows([]);setMessage('');setError('');setLoading(Boolean(account&&list));if(account&&list)api<any[]>('/api/reminders',undefined,undefined,undefined,account).then(v=>{if(active)setRows(v.filter(x=>x.status==='pending'));}).catch(()=>{if(active)setError(t.failed);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[account,list,revision,locale]);
 async function act(path:string,body?:unknown,method?:string){if(!account)return;const owner=account;setBusy(true);setError('');setMessage('');try{await api(path,body,method,undefined,owner);setMessage(method==='DELETE'?t.cancelled:t.saved);setRevision(v=>v+1);}catch(e){setError(displayFailure(e,locale));}finally{setBusy(false);}}
 const eligible=plan&&candidate&&reminderEligible(plan,candidate)&&Date.parse(candidate.departureAt)>Date.now();
 return <section className="panel reminder-controls" aria-label={t.title}><h3>{t.title}</h3><p className="micro-copy">{t.help}</p>
 {!account?<p>{t.signIn}</p>:list?<>{loading&&<Pending>{locale==='ar'?'جارٍ تحميل التذكيرات…':'Loading reminders…'}</Pending>}{error&&<><Notice>{error}</Notice><Button onClick={()=>setRevision(v=>v+1)}>{t.retry}</Button></>}{!rows.length&&!error&&!loading&&<p>{t.empty}</p>}{rows.map(row=><div key={row.id} className="reminder-row"><p>{row.plan.origin.displayName} → {row.plan.destination.displayName}<br/>{dateLabel(localDate(Date.parse(row.candidate.departureAt),row.plan.timezone),locale)} · <bdi>{clock(row.candidate.departureAt,row.plan.timezone,locale)} · {row.plan.timezone}</bdi></p><Button pending={busy} className="button secondary" onClick={()=>void act(`/api/reminders/${row.id}`,undefined,'DELETE')}>{t.cancel}</Button></div>)}</>:eligible?<><label>{t.lead}<select value={lead} onChange={e=>setLead(Number(e.target.value))}><option value={15}>15</option><option value={20}>20</option><option value={30}>30</option><option value={60}>60</option></select></label><Button pending={busy} disabled={!push} onClick={()=>void act('/api/reminders',{plan,candidate,locale,leadMinutes:lead})}>{t.save}</Button>{!push&&<p>{t.enable}</p>}</>:<p>{t.blocked}</p>}
 {!list&&error&&<Notice>{error}</Notice>}{message&&<p role="status">{message}</p>}</section>;
}
